version: "3"

services:

  db:
    image: mysql/mysql-server
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_USER=testjava
      - MYSQL_PASSWORD=testjava
