version: "3"

services:

  db_campaign:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=campaign
      - MYSQL_PASSWORD=campaign
      - MYSQL_DATABASE=campaigns

  db_user:
    image: mysql
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_DATABASE=users

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
