version: "3"

services:

  db1:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_USER=testjava
      - MYSQL_PASSWORD=testjava
      - MYSQL_DATABASE=testdb
  db2:
    image: mysql
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_USER=testjava
      - MYSQL_PASSWORD=testjava
      - MYSQL_DATABASE=testdb

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
